sudo: required

services:
 - docker

before_install:
 - docker pull jjhursey/pmix-standard

script:
 - docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/pmixer/governance jjhursey/pmix-standard
   /bin/bash -c "cp -R /home/pmixer/governance pmix-build && cd pmix-build && make"

# Notes:
#  - The container runs as a standard user 'pmixer'
#  - Need to copy `governance` to `pmix-build` because of file permissions issues
#    related to mounting the volume on certain OSs (i.e., OSX).
